### ISSUE TITLE
confusing text in readme

### ISSUE THREAD

**Issue by ian-kelling** [nikitakit/Kaleidoscope-ModifierLayers#1]
"For example in the Programmer Dvorak keyboard layout, the top row of the keyboard contains the symbols $&[{}(=*)+]!#, while numbers can be typed by pressing Shift and one of the symbols. The keys of the shifted and unshifted layers are rearranged independently when compared to a QWERTY layout."

I don't understand what "layers are rearranged" means. Layers in QUERTY are static, they are not rearranged. You could say that keys are rearranged by changing between layers. So, I definitely don't understand what "layers are rearranged independently" means.

**Comment by nikitakit** [comment]
QWERTY is QWERTY, but the key positions on Programmer Dvorak are nonstandard (rearranged). What this is saying is that the permutation needed to transform unshifted QWERTY to unshifted PDvorak is different from the permutation needed to transform shifted QWERTY to shifted PDVORAK, i.e. it's not enough to just change the base keymap and leave shift untouched.

**Comment by ian-kelling** [comment]
Thanks. I think it was mostly my fault on misreading.
